name: check

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  move:
    runs-on: runs-on,runner=2cpu-linux-x64,run-id=${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
      - uses: aptos-labs/actions/test-move@main
        with:
          WORKING_DIRECTORY: move
          ADDITIONAL_LINT_ARGS: --named-addresses addr=0x5
          ADDITIONAL_COMPILE_ARGS: --named-addresses addr=0x5
          ADDITIONAL_TEST_ARGS: --named-addresses addr=0x5
